name: Update Utopia Gist

on:
  workflow_dispatch: # allow manual trigger
  schedule:
    - cron: '0 0 1 * *' # monthly on the 1st at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch CSV and convert to JSON
        run: |
          curl -s "https://docs.google.com/spreadsheets/d/e/2PACX-1vT2NO2UixNebAWUPDGb1-q5Y3z7f4pMA8zJFVdRUCrP0FQWd2FuOsVwFMlmjtZyMzan-8v6wD6Cc84/pub?gid=615117949&single=true&output=csv" -o utopia.csv
      
          echo '{ "type": "module" }' > package.json
      
          cat << EOF > convert.mjs
          import fs from "fs";
      
          const csv = fs.readFileSync("utopia.csv", "utf-8").trim().split("\\n");
          const [headerLine, ...lines] = csv;
          const headers = headerLine.split(",");
      
          const dataset = {};
          for (const line of lines) {
            const values = line.split(",");
            const entry = Object.fromEntries(headers.map((h, i) => [h.trim(), values[i]?.trim() || ""]));
            const { Date: date, UID: uid } = entry;
            if (!dataset[date]) dataset[date] = {};
            dataset[date][uid] = entry;
          }
      
          fs.writeFileSync("utopia.json", JSON.stringify(dataset, null, 2));
          EOF
      
          node convert.mjs


      - name: Update Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: df83f58ece59cb4b35d830fd40594b67
          file_path: utopia.json
